package com.example.ruitongapp.beans;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ruitongapp.beans.FuWuQiBean;

import com.example.ruitongapp.beans.FuWuQiBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fuWuQiBeanDaoConfig;

    private final FuWuQiBeanDao fuWuQiBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fuWuQiBeanDaoConfig = daoConfigMap.get(FuWuQiBeanDao.class).clone();
        fuWuQiBeanDaoConfig.initIdentityScope(type);

        fuWuQiBeanDao = new FuWuQiBeanDao(fuWuQiBeanDaoConfig, this);

        registerDao(FuWuQiBean.class, fuWuQiBeanDao);
    }
    
    public void clear() {
        fuWuQiBeanDaoConfig.clearIdentityScope();
    }

    public FuWuQiBeanDao getFuWuQiBeanDao() {
        return fuWuQiBeanDao;
    }

}
